<?php
global $APPLICATION;
require($_SERVER['DOCUMENT_ROOT'] . '/bitrix/header.php');
$APPLICATION->SetTitle("Услуги");
?>

<?php
$APPLICATION->IncludeComponent(
	"bitrix:news", 
	"services_fix", 
	array(
		"DISPLAY_DATE" => "Y",
		"DISPLAY_PICTURE" => "N",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"SEF_MODE" => "Y",
		"AJAX_MODE" => "N",
		"IBLOCK_TYPE" => "ultrasale",
		"IBLOCK_ID" => "19",
		"NEWS_COUNT" => "60",
		"USE_SEARCH" => "N",
		"USE_RSS" => "N",
		"USE_RATING" => "N",
		"USE_CATEGORIES" => "N",
		"USE_REVIEW" => "N",
		"USE_FILTER" => "N",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_ORDER1" => "DESC",
		"SORT_BY2" => "SORT",
		"SORT_ORDER2" => "ASC",
		"CHECK_DATES" => "N",
		"PREVIEW_TRUNCATE_LEN" => "",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => array(
			0 => "DATE_CREATE",
			1 => "DESCRIPTION",
			2 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "",
			1 => "DATE",
			2 => "",
		),
		"HIDE_LINK_WHEN_NO_DETAIL" => "Y",
		"DISPLAY_NAME" => "Y",
		"META_KEYWORDS" => "-",
		"META_DESCRIPTION" => "-",
		"BROWSER_TITLE" => "-",
		"DETAIL_SET_CANONICAL_URL" => "Y",
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"DETAIL_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"DETAIL_PROPERTY_CODE" => array(
			0 => "",
			1 => "DATE",
			2 => "",
		),
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "N",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_SHOW_ALL" => "N",
		"STRICT_SECTION_CHECK" => "Y",
		"SET_TITLE" => "N",
		"ADD_SECTIONS_CHAIN" => "Y",
		"ADD_ELEMENT_CHAIN" => "Y",
		"SET_LAST_MODIFIED" => "Y",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SET_STATUS_404" => "Y",
		"SHOW_404" => "Y",
		"MESSAGE_404" => "",
		"PAGER_BASE_LINK" => "",
		"PAGER_PARAMS_NAME" => "arrPager",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"USE_PERMISSIONS" => "Y",
		"GROUP_PERMISSIONS" => array(
			0 => "2",
		),
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "3600",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "N",
		"DISPLAY_TOP_PAGER" => "Y",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Услуги",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "main",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "Y",
		"FILTER_NAME" => "",
		"FILTER_FIELD_CODE" => "",
		"FILTER_PROPERTY_CODE" => "",
		"NUM_NEWS" => "20",
		"NUM_DAYS" => "30",
		"YANDEX" => "N",
		"MAX_VOTE" => "5",
		"VOTE_NAMES" => array(
			0 => "0",
			1 => "1",
			2 => "2",
			3 => "3",
			4 => "4",
		),
		"CATEGORY_IBLOCK" => "",
		"CATEGORY_CODE" => "CATEGORY",
		"CATEGORY_ITEMS_COUNT" => "5",
		"MESSAGES_PER_PAGE" => "10",
		"USE_CAPTCHA" => "N",
		"REVIEW_AJAX_POST" => "N",
		"PATH_TO_SMILE" => "/bitrix/images/forum/smile/",
		"FORUM_ID" => "1",
		"URL_TEMPLATES_READ" => "",
		"SHOW_LINK_TO_FORUM" => "N",
		"POST_FIRST_MESSAGE" => "N",
		"SEF_FOLDER" => "/services/",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "N",
		"AJAX_OPTION_HISTORY" => "N",
		"USE_SHARE" => "N",
		"SHARE_HIDE" => "Y",
		"SHARE_TEMPLATE" => "",
		"SHARE_HANDLERS" => array(
			0 => "delicious",
			1 => "facebook",
			2 => "lj",
			3 => "twitter",
		),
		"SHARE_SHORTEN_URL_LOGIN" => "",
		"SHARE_SHORTEN_URL_KEY" => "",
		"COMPONENT_TEMPLATE" => "services_fix",
		"AJAX_OPTION_ADDITIONAL" => "",
		"FILE_404" => "",
		"SEF_URL_TEMPLATES" => array(
			"news" => "/",
			"section" => "#SECTION_CODE#/",
			"detail" => "#SECTION_CODE#/#ELEMENT_CODE#/",
		)
	),
	false
);
?>

<?php
$APPLICATION->IncludeComponent(
    "bitrix:news.list",
    "clients",
    array(
        "DISPLAY_DATE"                    => "N",
        "DISPLAY_NAME"                    => "Y",
        "DISPLAY_PICTURE"                 => "Y",
        "DISPLAY_PREVIEW_TEXT"            => "N",
        "AJAX_MODE"                       => "N",
        "IBLOCK_TYPE"                     => "ultrasale",
        "IBLOCK_ID"                       => "7",
        "NEWS_COUNT"                      => "16",
        "SORT_BY1"                        => "SORT",
        "SORT_ORDER1"                     => "DESC",
        "SORT_BY2"                        => "NAME",
        "SORT_ORDER2"                     => "ASC",
        "FILTER_NAME"                     => "",
        "FIELD_CODE"                      => array("ID", 'PREVIEW_PICTURE'),
        "PROPERTY_CODE"                   => array("DESCRIPTION"),
        "CHECK_DATES"                     => "Y",
        "DETAIL_URL"                      => "",
        "PREVIEW_TRUNCATE_LEN"            => "",
        "ACTIVE_DATE_FORMAT"              => "d.m.Y",
        "SET_TITLE"                       => "N",
        "SET_BROWSER_TITLE"               => "N",
        "SET_META_KEYWORDS"               => "N",
        "SET_META_DESCRIPTION"            => "N",
        "SET_LAST_MODIFIED"               => "N",
        "INCLUDE_IBLOCK_INTO_CHAIN"       => "N",
        "ADD_SECTIONS_CHAIN"              => "N",
        "HIDE_LINK_WHEN_NO_DETAIL"        => "N",
        "PARENT_SECTION"                  => "",
        "PARENT_SECTION_CODE"             => "",
        "INCLUDE_SUBSECTIONS"             => "N",
        "CACHE_TYPE"                      => "A",
        "CACHE_TIME"                      => "3600",
        "CACHE_FILTER"                    => "Y",
        "CACHE_GROUPS"                    => "Y",
        "DISPLAY_TOP_PAGER"               => "Y",
        "DISPLAY_BOTTOM_PAGER"            => "Y",
        "PAGER_TITLE"                     => "Клиенты",
        "PAGER_SHOW_ALWAYS"               => "N",
        "PAGER_TEMPLATE"                  => "",
        "PAGER_DESC_NUMBERING"            => "N",
        "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
        "PAGER_SHOW_ALL"                  => "N",
        "PAGER_BASE_LINK_ENABLE"          => "N",
        "SET_STATUS_404"                  => "N",
        "SHOW_404"                        => "N",
        "MESSAGE_404"                     => "",
        "PAGER_BASE_LINK"                 => "",
        "PAGER_PARAMS_NAME"               => "arrPager",
        "AJAX_OPTION_JUMP"                => "N",
        "AJAX_OPTION_STYLE"               => "N",
        "AJAX_OPTION_HISTORY"             => "N",
        "AJAX_OPTION_ADDITIONAL"          => "",
    )
);
?>

<?php
$APPLICATION->IncludeComponent(
    "bitrix:catalog.section.list",
    "objects_main",
    array(
        "IBLOCK_TYPE"         => "ultrasale",
        "IBLOCK_ID"           => "6",
        "SECTION_ID"          => "",
        "SECTION_CODE"        => "",
        "COUNT_ELEMENTS"      => "N",
        "TOP_DEPTH"           => "1",
        "SECTION_FIELDS"      => array(''),
        "SECTION_USER_FIELDS" => array('UF_DONE_COUNT'),
        "SECTION_URL"         => "",
        "CACHE_TYPE"          => "A",
        "CACHE_TIME"          => "36000000",
        "CACHE_NOTES"         => "",
        "CACHE_GROUPS"        => "Y",
        "ADD_SECTIONS_CHAIN"  => "Y",
    )
);
?>

<?php
$APPLICATION->IncludeComponent(
    "bitrix:news.list",
    "certificates",
    array(
        "DISPLAY_DATE"                    => "N",
        "DISPLAY_NAME"                    => "Y",
        "DISPLAY_PICTURE"                 => "Y",
        "DISPLAY_PREVIEW_TEXT"            => "N",
        "AJAX_MODE"                       => "N",
        "IBLOCK_TYPE"                     => "ultrasale",
        "IBLOCK_ID"                       => "8",
        "NEWS_COUNT"                      => "30",
        "SORT_BY1"                        => "SORT",
        "SORT_ORDER1"                     => "DESC",
        "SORT_BY2"                        => "NAME",
        "SORT_ORDER2"                     => "ASC",
        "FILTER_NAME"                     => "",
        "FIELD_CODE"                      => array("ID", 'PREVIEW_PICTURE', 'DETAIL_PICTURE'),
        "PROPERTY_CODE"                   => array("DESCRIPTION"),
        "CHECK_DATES"                     => "Y",
        "DETAIL_URL"                      => "",
        "PREVIEW_TRUNCATE_LEN"            => "",
        "ACTIVE_DATE_FORMAT"              => "d.m.Y",
        "SET_TITLE"                       => "N",
        "SET_BROWSER_TITLE"               => "N",
        "SET_META_KEYWORDS"               => "N",
        "SET_META_DESCRIPTION"            => "N",
        "SET_LAST_MODIFIED"               => "N",
        "INCLUDE_IBLOCK_INTO_CHAIN"       => "N",
        "ADD_SECTIONS_CHAIN"              => "N",
        "HIDE_LINK_WHEN_NO_DETAIL"        => "N",
        "PARENT_SECTION"                  => "",
        "PARENT_SECTION_CODE"             => "",
        "INCLUDE_SUBSECTIONS"             => "N",
        "CACHE_TYPE"                      => "A",
        "CACHE_TIME"                      => "3600",
        "CACHE_FILTER"                    => "Y",
        "CACHE_GROUPS"                    => "Y",
        "DISPLAY_TOP_PAGER"               => "Y",
        "DISPLAY_BOTTOM_PAGER"            => "Y",
        "PAGER_TITLE"                     => "Сертификаты",
        "PAGER_SHOW_ALWAYS"               => "N",
        "PAGER_TEMPLATE"                  => "",
        "PAGER_DESC_NUMBERING"            => "N",
        "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
        "PAGER_SHOW_ALL"                  => "N",
        "PAGER_BASE_LINK_ENABLE"          => "N",
        "SET_STATUS_404"                  => "N",
        "SHOW_404"                        => "N",
        "MESSAGE_404"                     => "",
        "PAGER_BASE_LINK"                 => "",
        "PAGER_PARAMS_NAME"               => "arrPager",
        "AJAX_OPTION_JUMP"                => "N",
        "AJAX_OPTION_STYLE"               => "N",
        "AJAX_OPTION_HISTORY"             => "N",
        "AJAX_OPTION_ADDITIONAL"          => "",
        "FANCYBOX_ID"                     => "",
    )
);
?>
<?php
    $APPLICATION->IncludeComponent(
    "bitrix:news.list",
    "client_reply",
    array(
    "DISPLAY_DATE"                    => "N",
    "DISPLAY_NAME"                    => "Y",
    "DISPLAY_PICTURE"                 => "Y",
    "DISPLAY_PREVIEW_TEXT"            => "N",
    "AJAX_MODE"                       => "N",
    "IBLOCK_TYPE"                     => "ultrasale",
    "IBLOCK_ID"                       => "9",
    "NEWS_COUNT"                      => "6",
    "SORT_BY1"                        => "SORT",
    "SORT_ORDER1"                     => "DESC",
    "SORT_BY2"                        => "NAME",
    "SORT_ORDER2"                     => "ASC",
    "FILTER_NAME"                     => "",
    "FIELD_CODE"                      => array("ID", 'PREVIEW_PICTURE', 'DETAIL_PICTURE'),
    "PROPERTY_CODE"                   => array("DESCRIPTION"),
    "CHECK_DATES"                     => "Y",
    "DETAIL_URL"                      => "",
    "PREVIEW_TRUNCATE_LEN"            => "",
    "ACTIVE_DATE_FORMAT"              => "d.m.Y",
    "SET_TITLE"                       => "N",
    "SET_BROWSER_TITLE"               => "N",
    "SET_META_KEYWORDS"               => "N",
    "SET_META_DESCRIPTION"            => "N",
    "SET_LAST_MODIFIED"               => "N",
    "INCLUDE_IBLOCK_INTO_CHAIN"       => "N",
    "ADD_SECTIONS_CHAIN"              => "N",
    "HIDE_LINK_WHEN_NO_DETAIL"        => "N",
    "PARENT_SECTION"                  => "",
    "PARENT_SECTION_CODE"             => "",
    "INCLUDE_SUBSECTIONS"             => "N",
    "CACHE_TYPE"                      => "A",
    "CACHE_TIME"                      => "3600",
    "CACHE_FILTER"                    => "Y",
    "CACHE_GROUPS"                    => "Y",
    "DISPLAY_TOP_PAGER"               => "Y",
    "DISPLAY_BOTTOM_PAGER"            => "Y",
    "PAGER_TITLE"                     => "Отзывы",
    "PAGER_SHOW_ALWAYS"               => "N",
    "PAGER_TEMPLATE"                  => "",
    "PAGER_DESC_NUMBERING"            => "N",
    "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
    "PAGER_SHOW_ALL"                  => "N",
    "PAGER_BASE_LINK_ENABLE"          => "N",
    "SET_STATUS_404"                  => "N",
    "SHOW_404"                        => "N",
    "MESSAGE_404"                     => "",
    "PAGER_BASE_LINK"                 => "",
    "PAGER_PARAMS_NAME"               => "arrPager",
    "AJAX_OPTION_JUMP"                => "N",
    "AJAX_OPTION_STYLE"               => "N",
    "AJAX_OPTION_HISTORY"             => "N",
    "AJAX_OPTION_ADDITIONAL"          => "",
    "FANCYBOX_ID"                     => "",
    )
    );
    ?>

<?php
$APPLICATION->IncludeComponent(
    "custom:form",
    "inline_app",
    array(
        'IBLOCK_ID'             => '5',
        'MAIL_EVENT'            => 'FORM_SENDED_2',
        'RECAPTCHA_ENABLED'     => 'Y',
        'RECAPTCHA_PUBLIC_KEY'  => '6LdW0fUcAAAAAOi-UR9ErNn8w1B2snuNI5wPnkrN',
        'RECAPTCHA_PRIVATE_KEY' => '6LdW0fUcAAAAADOwm4n6TrVJeqD7Xjc-IZDfV5p-',
        'ACTIVE'                => 'Y',
        'TOKEN'                 => 'inline_app001',
        'FORM_NAME'             => 'Свяжитесь с нами',
        'PROPS'                 => array(
            'NAME', // type - string
            'PHONE', // type - string
            'EMAIL', // type - string
            'FILE', // type - string
            'MESSAGE,TEXT', // type - html/text
        ),
    )
); ?>
<?php
$APPLICATION->IncludeFile(
    SITE_DIR . "local/include/about_bits.php",
    array(),
    array("MODE" => "html")
); ?>
<?php
require($_SERVER['DOCUMENT_ROOT'] . '/bitrix/footer.php');
